# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.nameisp.com/status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/parsers/whois.nameisp.com.rb'

describe Whois::Parsers::WhoisNameispCom, "status_registered.expected" do

  subject do
    file = fixture("responses", "whois.nameisp.com/status_registered.txt")
    part = Whois::Record::Part.new(body: File.read(file))
    described_class.new(part)
  end

  describe "#domain" do
    it do
      expect(subject.domain).to eq("nameisp.com")
    end
  end
  describe "#domain_id" do
    it do
      expect(subject.domain_id).to eq("93697156_DOMAIN_COM-VRSN")
    end
  end
  describe "#status" do
    it do
      expect(subject.status).to eq(:registered)
    end
  end
  describe "#available?" do
    it do
      expect(subject.available?).to eq(false)
    end
  end
  describe "#registered?" do
    it do
      expect(subject.registered?).to eq(true)
    end
  end
  describe "#created_on" do
    it do
      expect(subject.created_on).to be_a(Time)
      expect(subject.created_on).to eq(Time.parse("2003-01-06 13:49:20 UTC"))
    end
  end
  describe "#updated_on" do
    it do
      expect(subject.updated_on).to be_a(Time)
      expect(subject.updated_on).to eq(Time.parse("2017-03-20 10:43:48 UTC"))
    end
  end
  describe "#expires_on" do
    it do
      expect(subject.expires_on).to be_a(Time)
      expect(subject.expires_on).to eq(Time.parse("2025-01-06 13:49:20 UTC"))
    end
  end
  describe "#registrar" do
    it do
      expect(subject.registrar).to be_a(Whois::Parser::Registrar)
      expect(subject.registrar.id).to eq("1371")
      expect(subject.registrar.name).to eq("AB NAME ISP")
      expect(subject.registrar.organization).to eq("AB NAME ISP")
      expect(subject.registrar.url).to eq("www.namesrs.com")
    end
  end
  describe "#registrant_contacts" do
    it do
      expect(subject.registrant_contacts).to be_a(Array)
      expect(subject.registrant_contacts.size).to eq(1)
      expect(subject.registrant_contacts[0]).to be_a(Whois::Parser::Contact)
      expect(subject.registrant_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_REGISTRANT)
      expect(subject.registrant_contacts[0].name).to eq("Domain Admin")
      expect(subject.registrant_contacts[0].organization).to eq("AB Name ISP")
      expect(subject.registrant_contacts[0].address).to eq("Radiovgen 2")
      expect(subject.registrant_contacts[0].city).to eq("VSTRA FRLUNDA")
      expect(subject.registrant_contacts[0].zip).to eq("421 47")
      expect(subject.registrant_contacts[0].state).to eq("")
      expect(subject.registrant_contacts[0].country_code).to eq("SE")
      expect(subject.registrant_contacts[0].phone).to eq("+46.313011220")
      expect(subject.registrant_contacts[0].fax).to eq("+46.317090850")
      expect(subject.registrant_contacts[0].email).to eq("registry@nameisp.com")
    end
  end
  describe "#admin_contacts" do
    it do
      expect(subject.admin_contacts).to be_a(Array)
      expect(subject.admin_contacts.size).to eq(1)
      expect(subject.admin_contacts[0]).to be_a(Whois::Parser::Contact)
      expect(subject.admin_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_ADMINISTRATIVE)
      expect(subject.admin_contacts[0].name).to eq("Domain Admin")
      expect(subject.admin_contacts[0].organization).to eq("AB Name ISP")
      expect(subject.admin_contacts[0].address).to eq("Radiovgen 2")
      expect(subject.admin_contacts[0].city).to eq("VSTRA FRLUNDA")
      expect(subject.admin_contacts[0].zip).to eq("421 47")
      expect(subject.admin_contacts[0].state).to eq("")
      expect(subject.admin_contacts[0].country_code).to eq("se")
      expect(subject.admin_contacts[0].phone).to eq("+46.313011220")
      expect(subject.admin_contacts[0].fax).to eq("+46.317090850")
      expect(subject.admin_contacts[0].email).to eq("registry@nameisp.com")
    end
  end
  describe "#technical_contacts" do
    it do
      expect(subject.technical_contacts).to be_a(Array)
      expect(subject.technical_contacts.size).to eq(1)
      expect(subject.technical_contacts[0]).to be_a(Whois::Parser::Contact)
      expect(subject.technical_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_TECHNICAL)
      expect(subject.technical_contacts[0].name).to eq("Domain Admin")
      expect(subject.technical_contacts[0].organization).to eq("AB Name ISP")
      expect(subject.technical_contacts[0].address).to eq("Radiovgen 2")
      expect(subject.technical_contacts[0].city).to eq("VSTRA FRLUNDA")
      expect(subject.technical_contacts[0].zip).to eq("421 47")
      expect(subject.technical_contacts[0].state).to eq("")
      expect(subject.technical_contacts[0].country_code).to eq("SE")
      expect(subject.technical_contacts[0].phone).to eq("+46.313011220")
      expect(subject.technical_contacts[0].fax).to eq("+46.317090850")
      expect(subject.technical_contacts[0].email).to eq("registry@nameisp.com")
    end
  end
  describe "#nameservers" do
    it do
      expect(subject.nameservers).to be_a(Array)
      expect(subject.nameservers.size).to eq(2)
      expect(subject.nameservers[0]).to be_a(Whois::Parser::Nameserver)
      expect(subject.nameservers[0].name).to eq("gene.ns.cloudflare.com")
      expect(subject.nameservers[1]).to be_a(Whois::Parser::Nameserver)
      expect(subject.nameservers[1].name).to eq("tim.ns.cloudflare.com")
    end
  end
end
