# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.cctld.uz/uz/property_expires_on_dash.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/parsers/whois.cctld.uz.rb'

describe Whois::Parsers::WhoisCctldUz, "property_expires_on_dash.expected" do

  subject do
    file = fixture("responses", "whois.cctld.uz/uz/property_expires_on_dash.txt")
    part = Whois::Record::Part.new(body: File.read(file))
    described_class.new(part)
  end

  describe "#expires_on" do
    it do
      expect(subject.expires_on).to eq(nil)
    end
  end
end
