# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.ilait.com/status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/parsers/whois.ilait.com.rb'

describe Whois::Parsers::WhoisIlaitCom, "status_registered.expected" do

  subject do
    file = fixture("responses", "whois.ilait.com/status_registered.txt")
    part = Whois::Record::Part.new(body: File.read(file))
    described_class.new(part)
  end

  describe "#domain" do
    it do
      expect(subject.domain).to eq("ilait.com")
    end
  end
  describe "#domain_id" do
    it do
      expect(subject.domain_id).to eq("564826693_DOMAIN_COM-VRSN")
    end
  end
  describe "#status" do
    it do
      expect(subject.status).to eq(:registered)
    end
  end
  describe "#available?" do
    it do
      expect(subject.available?).to eq(false)
    end
  end
  describe "#registered?" do
    it do
      expect(subject.registered?).to eq(true)
    end
  end
  describe "#created_on" do
    it do
      expect(subject.created_on).to be_a(Time)
      expect(subject.created_on).to eq(Time.parse("2006-08-22 15:43:04 UTC"))
    end
  end
  describe "#updated_on" do
    it do
      expect(subject.updated_on).to be_a(Time)
      expect(subject.updated_on).to eq(Time.parse("2014-09-17 14:09:03 UTC"))
    end
  end
  describe "#expires_on" do
    it do
      expect(subject.expires_on).to be_a(Time)
      expect(subject.expires_on).to eq(Time.parse("2019-08-22 15:43:04 UTC"))
    end
  end
  describe "#registrar" do
    it do
      expect(subject.registrar).to be_a(Whois::Parser::Registrar)
      expect(subject.registrar.id).to eq("1493")
      expect(subject.registrar.name).to eq("ilait AB")
      expect(subject.registrar.organization).to eq("ilait AB")
      expect(subject.registrar.url).to eq("http://www.ilait.se")
    end
  end
  describe "#registrant_contacts" do
    it do
      expect(subject.registrant_contacts).to be_a(Array)
      expect(subject.registrant_contacts.size).to eq(1)
      expect(subject.registrant_contacts[0]).to be_a(Whois::Parser::Contact)
      expect(subject.registrant_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_REGISTRANT)
      expect(subject.registrant_contacts[0].name).to eq("ilait Registry")
      expect(subject.registrant_contacts[0].organization).to eq("ilait AB")
      expect(subject.registrant_contacts[0].address).to eq("Truckgatan 13")
      expect(subject.registrant_contacts[0].city).to eq("Kungälv")
      expect(subject.registrant_contacts[0].zip).to eq("44240")
      expect(subject.registrant_contacts[0].state).to eq("")
      expect(subject.registrant_contacts[0].country_code).to eq("SE")
      expect(subject.registrant_contacts[0].phone).to eq("+46.313522300")
      expect(subject.registrant_contacts[0].fax).to eq("+46.313522301")
      expect(subject.registrant_contacts[0].email).to eq("registry@ilait.se")
    end
  end
  describe "#admin_contacts" do
    it do
      expect(subject.admin_contacts).to be_a(Array)
      expect(subject.admin_contacts.size).to eq(1)
      expect(subject.admin_contacts[0]).to be_a(Whois::Parser::Contact)
      expect(subject.admin_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_ADMINISTRATIVE)
      expect(subject.admin_contacts[0].name).to eq("ilait Registry")
      expect(subject.admin_contacts[0].organization).to eq("ilait AB")
      expect(subject.admin_contacts[0].address).to eq("Truckgatan 13")
      expect(subject.admin_contacts[0].city).to eq("Kungälv")
      expect(subject.admin_contacts[0].zip).to eq("44240")
      expect(subject.admin_contacts[0].state).to eq("")
      expect(subject.admin_contacts[0].country_code).to eq("SE")
      expect(subject.admin_contacts[0].phone).to eq("+46.313522300")
      expect(subject.admin_contacts[0].fax).to eq("+46.313522301")
      expect(subject.admin_contacts[0].email).to eq("registry@ilait.se")
    end
  end
  describe "#technical_contacts" do
    it do
      expect(subject.technical_contacts).to be_a(Array)
      expect(subject.technical_contacts.size).to eq(1)
      expect(subject.technical_contacts[0]).to be_a(Whois::Parser::Contact)
      expect(subject.technical_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_TECHNICAL)
      expect(subject.technical_contacts[0].name).to eq("ilait Registry")
      expect(subject.technical_contacts[0].organization).to eq("ilait AB")
      expect(subject.technical_contacts[0].address).to eq("Truckgatan 13")
      expect(subject.technical_contacts[0].city).to eq("Kungälv")
      expect(subject.technical_contacts[0].zip).to eq("44240")
      expect(subject.technical_contacts[0].state).to eq("")
      expect(subject.technical_contacts[0].country_code).to eq("SE")
      expect(subject.technical_contacts[0].phone).to eq("+46.313522300")
      expect(subject.technical_contacts[0].fax).to eq("+46.313522301")
      expect(subject.technical_contacts[0].email).to eq("registry@ilait.se")
    end
  end
  describe "#nameservers" do
    it do
      expect(subject.nameservers).to be_a(Array)
      expect(subject.nameservers.size).to eq(4)
      expect(subject.nameservers[0]).to be_a(Whois::Parser::Nameserver)
      expect(subject.nameservers[0].name).to eq("ns1.ilait.se")
      expect(subject.nameservers[1]).to be_a(Whois::Parser::Nameserver)
      expect(subject.nameservers[1].name).to eq("ns2.ilait.se")
      expect(subject.nameservers[2]).to be_a(Whois::Parser::Nameserver)
      expect(subject.nameservers[2].name).to eq("ns3.ilait.se")
      expect(subject.nameservers[3]).to be_a(Whois::Parser::Nameserver)
      expect(subject.nameservers[3].name).to eq("ns4.ilait.se")
    end
  end
end
