# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.corehub.net/status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/parsers/whois.corehub.net.rb'

describe Whois::Parsers::WhoisCorehubNet, "status_registered.expected" do

  subject do
    file = fixture("responses", "whois.corehub.net/status_registered.txt")
    part = Whois::Record::Part.new(body: File.read(file))
    described_class.new(part)
  end

  describe "#domain" do
    it do
      expect(subject.domain).to eq("corehub.net")
    end
  end
  describe "#domain_id" do
    it do
      expect(subject.domain_id).to eq("D-179116748-CONE")
    end
  end
  describe "#status" do
    it do
      expect(subject.status).to eq(:registered)
    end
  end
  describe "#available?" do
    it do
      expect(subject.available?).to eq(false)
    end
  end
  describe "#registered?" do
    it do
      expect(subject.registered?).to eq(true)
    end
  end
  describe "#created_on" do
    it do
      expect(subject.created_on).to be_a(Time)
      expect(subject.created_on).to eq(Time.parse("2012-07-14 16:04:42 UTC"))
    end
  end
  describe "#expires_on" do
    it do
      expect(subject.expires_on).to be_a(Time)
      expect(subject.expires_on).to eq(Time.parse("2018-07-14 16:04:42 UTC"))
    end
  end
  describe "#registrar" do
    it do
      expect(subject.registrar).to be_a(Whois::Parser::Registrar)
      expect(subject.registrar.id).to eq("15")
      expect(subject.registrar.name).to eq("CORE-901 (Axone/Secretariat Maintenance Account)")
      expect(subject.registrar.organization).to eq("CORE-901 (Axone/Secretariat Maintenance Account)")
      expect(subject.registrar.url).to eq("http://corehub.net")
    end
  end
  describe "#registrant_contacts" do
    it do
      expect(subject.registrant_contacts).to be_a(Array)
      expect(subject.registrant_contacts.size).to eq(1)
      expect(subject.registrant_contacts[0]).to be_a(Whois::Parser::Contact)
      expect(subject.registrant_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_REGISTRANT)
      expect(subject.registrant_contacts[0].name).to eq("CORE ASSOCIATION")
      expect(subject.registrant_contacts[0].organization).to eq("")
      expect(subject.registrant_contacts[0].address).to eq("")
      expect(subject.registrant_contacts[0].city).to eq("Geneva")
      expect(subject.registrant_contacts[0].zip).to eq("CH-1215")
      expect(subject.registrant_contacts[0].state).to eq("GE")
      expect(subject.registrant_contacts[0].country_code).to eq("CH")
      expect(subject.registrant_contacts[0].phone).to eq("+41.229295744")
      expect(subject.registrant_contacts[0].fax).to eq("+41.229295745")
      expect(subject.registrant_contacts[0].email).to eq("secretariat@corenic.org")
    end
  end
  describe "#admin_contacts" do
    it do
      expect(subject.admin_contacts).to be_a(Array)
      expect(subject.admin_contacts.size).to eq(1)
      expect(subject.admin_contacts[0]).to be_a(Whois::Parser::Contact)
      expect(subject.admin_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_ADMINISTRATIVE)
      expect(subject.admin_contacts[0].name).to eq("CORE Secretariat")
      expect(subject.admin_contacts[0].organization).to eq("CORE Association")
      expect(subject.admin_contacts[0].address).to eq("cour de Rive 2")
      expect(subject.admin_contacts[0].city).to eq("Geneve")
      expect(subject.admin_contacts[0].zip).to eq("1204")
      expect(subject.admin_contacts[0].state).to eq("GE")
      expect(subject.admin_contacts[0].country_code).to eq("CH")
      expect(subject.admin_contacts[0].phone).to eq("+41.223125610")
      expect(subject.admin_contacts[0].fax).to eq("")
      expect(subject.admin_contacts[0].email).to eq("secretariat@corenic.org")
    end
  end
  describe "#technical_contacts" do
    it do
      expect(subject.technical_contacts).to be_a(Array)
      expect(subject.technical_contacts.size).to eq(1)
      expect(subject.technical_contacts[0]).to be_a(Whois::Parser::Contact)
      expect(subject.technical_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_TECHNICAL)
      expect(subject.technical_contacts[0].name).to eq("CORE Secretariat")
      expect(subject.technical_contacts[0].organization).to eq("CORE Association")
      expect(subject.technical_contacts[0].address).to eq("cour de Rive 2")
      expect(subject.technical_contacts[0].city).to eq("Geneve")
      expect(subject.technical_contacts[0].zip).to eq("1204")
      expect(subject.technical_contacts[0].state).to eq("GE")
      expect(subject.technical_contacts[0].country_code).to eq("CH")
      expect(subject.technical_contacts[0].phone).to eq("+41.223125610")
      expect(subject.technical_contacts[0].fax).to eq("")
      expect(subject.technical_contacts[0].email).to eq("secretariat@corenic.org")
    end
  end
  describe "#nameservers" do
    it do
      expect(subject.nameservers).to be_a(Array)
      expect(subject.nameservers.size).to eq(3)
      expect(subject.nameservers[0]).to be_a(Whois::Parser::Nameserver)
      expect(subject.nameservers[0].name).to eq("us20-west.irondns.net")
      expect(subject.nameservers[0].ipv4).to eq("104.225.5.66")
      expect(subject.nameservers[0].ipv6).to eq("2607:fc50:2000:2001::2")
      expect(subject.nameservers[1]).to be_a(Whois::Parser::Nameserver)
      expect(subject.nameservers[1].name).to eq("hk21.irondns.net")
      expect(subject.nameservers[1].ipv4).to eq("103.6.86.97")
      expect(subject.nameservers[1].ipv6).to eq("2403:2500:8000:1::9f9")
      expect(subject.nameservers[2]).to be_a(Whois::Parser::Nameserver)
      expect(subject.nameservers[2].name).to eq("us19-east.irondns.net")
      expect(subject.nameservers[2].ipv4).to eq("4.71.215.210")
      expect(subject.nameservers[2].ipv6).to eq("2001:1900:2236::d2")
    end
  end
end
