# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.nominalia.com/status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/parsers/whois.nominalia.com.rb'

describe Whois::Parsers::WhoisNominaliaCom, "status_registered.expected" do

  subject do
    file = fixture("responses", "whois.nominalia.com/status_registered.txt")
    part = Whois::Record::Part.new(body: File.read(file))
    described_class.new(part)
  end

  describe "#domain" do
    it do
      expect(subject.domain).to eq("nominalia.com")
    end
  end
  describe "#domain_id" do
    it do
      expect(subject.domain_id).to eq("4546874_DOMAIN_COM-VRSN")
    end
  end
  describe "#status" do
    it do
      expect(subject.status).to eq(:registered)
    end
  end
  describe "#available?" do
    it do
      expect(subject.available?).to eq(false)
    end
  end
  describe "#registered?" do
    it do
      expect(subject.registered?).to eq(true)
    end
  end
  describe "#created_on" do
    it do
      expect(subject.created_on).to be_a(Time)
      expect(subject.created_on).to eq(Time.parse("2008-02-07 00:00:00 UTC"))
    end
  end
  describe "#updated_on" do
    it do
      expect(subject.updated_on).to be_a(Time)
      expect(subject.updated_on).to eq(Time.parse("2013-06-27 00:00:00 UTC"))
    end
  end
  describe "#expires_on" do
    it do
      expect(subject.expires_on).to be_a(Time)
      expect(subject.expires_on).to eq(Time.parse("2018-11-30 00:00:00 UTC"))
    end
  end
  describe "#registrar" do
    it do
      expect(subject.registrar).to be_a(Whois::Parser::Registrar)
      expect(subject.registrar.id).to eq("76")
      expect(subject.registrar.name).to eq("NOMINALIA INTERNET S.L.")
      expect(subject.registrar.organization).to eq("NOMINALIA INTERNET S.L.")
      expect(subject.registrar.url).to eq("http://www.nominalia.com")
    end
  end
  describe "#registrant_contacts" do
    it do
      expect(subject.registrant_contacts).to be_a(Array)
      expect(subject.registrant_contacts.size).to eq(1)
      expect(subject.registrant_contacts[0]).to be_a(Whois::Parser::Contact)
      expect(subject.registrant_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_REGISTRANT)
      expect(subject.registrant_contacts[0].name).to eq("Nominalia Internet S.L.")
      expect(subject.registrant_contacts[0].organization).to eq("Nominalia Internet S.L.")
      expect(subject.registrant_contacts[0].address).to eq("Josep Pla, 2. Torres Diagonal Litoral, B3, 3D")
      expect(subject.registrant_contacts[0].city).to eq("Barcelona")
      expect(subject.registrant_contacts[0].zip).to eq("ES-08019")
      expect(subject.registrant_contacts[0].state).to eq("B")
      expect(subject.registrant_contacts[0].country_code).to eq("ES")
      expect(subject.registrant_contacts[0].phone).to eq("+34.935074360")
      expect(subject.registrant_contacts[0].fax).to eq("+34.933102360")
      expect(subject.registrant_contacts[0].email).to eq("gestiontld@nominalia.com")
    end
  end
  describe "#admin_contacts" do
    it do
      expect(subject.admin_contacts).to be_a(Array)
      expect(subject.admin_contacts.size).to eq(1)
      expect(subject.admin_contacts[0]).to be_a(Whois::Parser::Contact)
      expect(subject.admin_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_ADMINISTRATIVE)
      expect(subject.admin_contacts[0].name).to eq("Claudio Corbetta")
      expect(subject.admin_contacts[0].organization).to eq("Nominalia Internet S.L.")
      expect(subject.admin_contacts[0].address).to eq("Josep Pla, 2. Torres Diagonal Litoral, B3, 3D")
      expect(subject.admin_contacts[0].city).to eq("Barcelona")
      expect(subject.admin_contacts[0].zip).to eq("08019")
      expect(subject.admin_contacts[0].state).to eq("B")
      expect(subject.admin_contacts[0].country_code).to eq("ES")
      expect(subject.admin_contacts[0].phone).to eq("+34.935074360")
      expect(subject.admin_contacts[0].fax).to eq("+34.933102360")
      expect(subject.admin_contacts[0].email).to eq("gestiontld@nominalia.com")
    end
  end
  describe "#technical_contacts" do
    it do
      expect(subject.technical_contacts).to be_a(Array)
      expect(subject.technical_contacts.size).to eq(1)
      expect(subject.technical_contacts[0]).to be_a(Whois::Parser::Contact)
      expect(subject.technical_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_TECHNICAL)
      expect(subject.technical_contacts[0].name).to eq("Billing Department")
      expect(subject.technical_contacts[0].organization).to eq("Nominalia Internet, S.L.")
      expect(subject.technical_contacts[0].address).to eq("Josep Pla, 2. Torres Diagonal Litoral. Edificio B3, planta 3-D")
      expect(subject.technical_contacts[0].city).to eq("Barcelona")
      expect(subject.technical_contacts[0].zip).to eq("08019")
      expect(subject.technical_contacts[0].state).to eq("Barcelona")
      expect(subject.technical_contacts[0].country_code).to eq("ES")
      expect(subject.technical_contacts[0].phone).to eq("+34.935074360")
      expect(subject.technical_contacts[0].fax).to eq("+34.933102360")
      expect(subject.technical_contacts[0].email).to eq("payment@nominalia.com")
    end
  end
  describe "#nameservers" do
    it do
      expect(subject.nameservers).to be_a(Array)
      expect(subject.nameservers.size).to eq(2)
      expect(subject.nameservers[0]).to be_a(Whois::Parser::Nameserver)
      expect(subject.nameservers[0].name).to eq("dns1.nominalia.com")
      expect(subject.nameservers[1]).to be_a(Whois::Parser::Nameserver)
      expect(subject.nameservers[1].name).to eq("dns2.nominalia.com")
    end
  end
end
