# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.joker.com/status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/parsers/whois.joker.com.rb'

describe Whois::Parsers::WhoisJokerCom, "status_registered.expected" do

  subject do
    file = fixture("responses", "whois.joker.com/status_registered.txt")
    part = Whois::Record::Part.new(body: File.read(file))
    described_class.new(part)
  end

  describe "#domain" do
    it do
      expect(subject.domain).to eq("joker.com")
    end
  end
  describe "#domain_id" do
    it do
      expect(subject.domain_id).to eq("523683_DOMAIN_COM-VRSN")
    end
  end
  describe "#status" do
    it do
      expect(subject.status).to eq(:registered)
    end
  end
  describe "#available?" do
    it do
      expect(subject.available?).to eq(false)
    end
  end
  describe "#registered?" do
    it do
      expect(subject.registered?).to eq(true)
    end
  end
  describe "#created_on" do
    it do
      expect(subject.created_on).to be_a(Time)
      expect(subject.created_on).to eq(Time.parse("1994-11-27 00:00:00 UTC"))
    end
  end
  describe "#updated_on" do
    it do
      expect(subject.updated_on).to be_a(Time)
      expect(subject.updated_on).to eq(Time.parse("2018-02-21 18:51:25 UTC"))
    end
  end
  describe "#expires_on" do
    it do
      expect(subject.expires_on).to be_a(Time)
      expect(subject.expires_on).to eq(Time.parse("2027-08-03 15:02:10 UTC"))
    end
  end
  describe "#registrar" do
    it do
      expect(subject.registrar).to be_a(Whois::Parser::Registrar)
      expect(subject.registrar.id).to eq("113")
      expect(subject.registrar.name).to eq("CSL Computer Service Langenbach GmbH d/b/a joker.com")
      expect(subject.registrar.organization).to eq("CSL Computer Service Langenbach GmbH d/b/a joker.com")
      expect(subject.registrar.url).to eq("http://joker.com/")
    end
  end
  describe "#registrant_contacts" do
    it do
      expect(subject.registrant_contacts).to be_a(Array)
      expect(subject.registrant_contacts.size).to eq(1)
      expect(subject.registrant_contacts[0]).to be_a(Whois::Parser::Contact)
      expect(subject.registrant_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_REGISTRANT)
      expect(subject.registrant_contacts[0].name).to eq("Domain Administrator")
      expect(subject.registrant_contacts[0].organization).to eq("CSL Computer Service Langenbach GmbH")
      expect(subject.registrant_contacts[0].address).to eq("Hansaallee 191-193")
      expect(subject.registrant_contacts[0].city).to eq("Duesseldorf")
      expect(subject.registrant_contacts[0].zip).to eq("40549")
      expect(subject.registrant_contacts[0].state).to eq("")
      expect(subject.registrant_contacts[0].country_code).to eq("DE")
      expect(subject.registrant_contacts[0].phone).to eq("+49.211867670")
      expect(subject.registrant_contacts[0].fax).to eq("+49.2118676710")
      expect(subject.registrant_contacts[0].email).to eq("admin@joker.com")
    end
  end
  describe "#admin_contacts" do
    it do
      expect(subject.admin_contacts).to be_a(Array)
      expect(subject.admin_contacts.size).to eq(1)
      expect(subject.admin_contacts[0]).to be_a(Whois::Parser::Contact)
      expect(subject.admin_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_ADMINISTRATIVE)
      expect(subject.admin_contacts[0].name).to eq("n/a")
      expect(subject.admin_contacts[0].organization).to eq("CSL Computer Service Langenbach GmbH")
      expect(subject.admin_contacts[0].address).to eq("Hansaallee 191-193")
      expect(subject.admin_contacts[0].city).to eq("Duesseldorf")
      expect(subject.admin_contacts[0].zip).to eq("40549")
      expect(subject.admin_contacts[0].state).to eq("")
      expect(subject.admin_contacts[0].country_code).to eq("DE")
      expect(subject.admin_contacts[0].phone).to eq("+49.211867670")
      expect(subject.admin_contacts[0].fax).to eq("")
      expect(subject.admin_contacts[0].email).to eq("admin@joker.com")
    end
  end
  describe "#technical_contacts" do
    it do
      expect(subject.technical_contacts).to be_a(Array)
      expect(subject.technical_contacts.size).to eq(1)
      expect(subject.technical_contacts[0]).to be_a(Whois::Parser::Contact)
      expect(subject.technical_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_TECHNICAL)
      expect(subject.technical_contacts[0].name).to eq("Domain Administrator")
      expect(subject.technical_contacts[0].organization).to eq("CSL Computer Service Langenbach GmbH")
      expect(subject.technical_contacts[0].address).to eq("Hansaallee 191-193")
      expect(subject.technical_contacts[0].city).to eq("Duesseldorf")
      expect(subject.technical_contacts[0].zip).to eq("40549")
      expect(subject.technical_contacts[0].state).to eq("NRW")
      expect(subject.technical_contacts[0].country_code).to eq("DE")
      expect(subject.technical_contacts[0].phone).to eq("+49.211867670")
      expect(subject.technical_contacts[0].fax).to eq("+49.2118676710")
      expect(subject.technical_contacts[0].email).to eq("hostmaster@joker.com")
    end
  end
  describe "#nameservers" do
    it do
      expect(subject.nameservers).to be_a(Array)
      expect(subject.nameservers.size).to eq(3)
      expect(subject.nameservers[0]).to be_a(Whois::Parser::Nameserver)
      expect(subject.nameservers[0].name).to eq("j.ns.joker.com")
      expect(subject.nameservers[1]).to be_a(Whois::Parser::Nameserver)
      expect(subject.nameservers[1].name).to eq("k.ns.joker.com")
      expect(subject.nameservers[2]).to be_a(Whois::Parser::Nameserver)
      expect(subject.nameservers[2].name).to eq("l.ns.joker.com")
    end
  end
end
