# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.domain.com/com/status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/parsers/whois.domain.com.rb'

describe Whois::Parsers::WhoisDomainCom, "status_registered.expected" do

  subject do
    file = fixture("responses", "whois.domain.com/com/status_registered.txt")
    part = Whois::Record::Part.new(body: File.read(file))
    described_class.new(part)
  end

  describe "#status" do
    it do
      expect(subject.status).to eq(:registered)
    end
  end
  describe "#available?" do
    it do
      expect(subject.available?).to eq(false)
    end
  end
  describe "#registered?" do
    it do
      expect(subject.registered?).to eq(true)
    end
  end
  describe "#created_on" do
    it do
      expect(subject.created_on).to be_a(Time)
      expect(subject.created_on).to eq(Time.parse("2016-05-12T09:25:07Z"))
    end
  end
  describe "#updated_on" do
    it do
      expect(subject.updated_on).to be_a(Time)
      expect(subject.updated_on).to eq(Time.parse("2016-05-13T16:25:54Z"))
    end
  end
  describe "#expires_on" do
    it do
      expect(subject.expires_on).to be_a(Time)
      expect(subject.expires_on).to eq(Time.parse("2017-05-12T09:25:07Z"))
    end
  end
  describe "#registrar" do
    it do
      expect(subject.registrar).to be_a(Whois::Parser::Registrar)
      expect(subject.registrar.id).to eq("886")
      expect(subject.registrar.name).to eq("Domain.com, LLC")
      expect(subject.registrar.organization).to eq("Domain.com, LLC")
      expect(subject.registrar.url).to eq("www.domain.com")
    end
  end
  describe "#registrant_contacts" do
    it do
      expect(subject.registrant_contacts).to be_a(Array)
      expect(subject.registrant_contacts.size).to eq(1)
      expect(subject.registrant_contacts[0]).to be_a(Whois::Parser::Contact)
      expect(subject.registrant_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_REGISTRANT)
      expect(subject.registrant_contacts[0].id).to eq(nil)
      expect(subject.registrant_contacts[0].name).to eq("Andreea Luisa")
      expect(subject.registrant_contacts[0].organization).to eq("bluebuckwoodworking")
      expect(subject.registrant_contacts[0].address).to eq("Aleea Luptatorilor, nr 32")
      expect(subject.registrant_contacts[0].city).to eq("Bucuresti")
      expect(subject.registrant_contacts[0].zip).to eq("021447")
      expect(subject.registrant_contacts[0].state).to eq("NA")
      expect(subject.registrant_contacts[0].country).to eq(nil)
      expect(subject.registrant_contacts[0].country_code).to eq("RO")
      expect(subject.registrant_contacts[0].phone).to eq("+40.0744222769")
      expect(subject.registrant_contacts[0].email).to eq("bluebuckwood@mail.com")
    end
  end
  describe "#admin_contacts" do
    it do
      expect(subject.admin_contacts).to be_a(Array)
      expect(subject.admin_contacts.size).to eq(1)
      expect(subject.admin_contacts[0]).to be_a(Whois::Parser::Contact)
      expect(subject.admin_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_ADMINISTRATIVE)
      expect(subject.admin_contacts[0].id).to eq(nil)
      expect(subject.admin_contacts[0].name).to eq("Andreea Luisa")
      expect(subject.admin_contacts[0].organization).to eq("bluebuckwoodworking")
      expect(subject.admin_contacts[0].address).to eq("Aleea Luptatorilor, nr 32")
      expect(subject.admin_contacts[0].city).to eq("Bucuresti")
      expect(subject.admin_contacts[0].zip).to eq("021447")
      expect(subject.admin_contacts[0].state).to eq("NA")
      expect(subject.admin_contacts[0].country).to eq(nil)
      expect(subject.admin_contacts[0].country_code).to eq("RO")
      expect(subject.admin_contacts[0].phone).to eq("+40.0744222769")
      expect(subject.admin_contacts[0].email).to eq("bluebuckwood@mail.com")
    end
  end
  describe "#technical_contacts" do
    it do
      expect(subject.technical_contacts).to be_a(Array)
      expect(subject.technical_contacts.size).to eq(1)
      expect(subject.technical_contacts[0]).to be_a(Whois::Parser::Contact)
      expect(subject.technical_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_TECHNICAL)
      expect(subject.technical_contacts[0].id).to eq(nil)
      expect(subject.technical_contacts[0].name).to eq("Andreea Luisa")
      expect(subject.technical_contacts[0].organization).to eq("bluebuckwoodworking")
      expect(subject.technical_contacts[0].address).to eq("Aleea Luptatorilor, nr 32")
      expect(subject.technical_contacts[0].city).to eq("Bucuresti")
      expect(subject.technical_contacts[0].zip).to eq("021447")
      expect(subject.technical_contacts[0].state).to eq("NA")
      expect(subject.technical_contacts[0].country).to eq(nil)
      expect(subject.technical_contacts[0].country_code).to eq("RO")
      expect(subject.technical_contacts[0].phone).to eq("+40.0744222769")
      expect(subject.technical_contacts[0].email).to eq("bluebuckwood@mail.com")
    end
  end
  describe "#nameservers" do
    it do
      expect(subject.nameservers).to be_a(Array)
      expect(subject.nameservers.size).to eq(2)
      expect(subject.nameservers[0]).to be_a(Whois::Parser::Nameserver)
      expect(subject.nameservers[0].name).to eq("ns1.host-care.com")
      expect(subject.nameservers[0].ipv4).to eq(nil)
      expect(subject.nameservers[0].ipv6).to eq(nil)
      expect(subject.nameservers[1]).to be_a(Whois::Parser::Nameserver)
      expect(subject.nameservers[1].name).to eq("ns2.host-care.com")
      expect(subject.nameservers[1].ipv4).to eq(nil)
      expect(subject.nameservers[1].ipv6).to eq(nil)
    end
  end
end
